plugins {
    id 'java'
    id 'uk.gov.hmcts.java' version '0.12.63'
    id 'io.gatling.gradle' version '3.11.5.2'
}

group = 'uk.gov.hmcts'
version = '0.0.1'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencyCheck {
    suppressionFile = 'config/owasp/suppressions.xml'
}

dependencies {
    gatling group: 'org.postgresql', name: 'postgresql', version: '42.7.4'
    gatling 'com.github.hmcts:juror-generation-support-library:1.5.4'
}

// Default gatlingRun configuration
gatlingRun {
    jvmArgs = ['-Xms512M', '-Xmx2G']
    //jvmArgs = ['-Xms4G', '-Xmx8G']
    simulationClassName = System.getenv("SimulationBlock")
    doFirst {
        println "Running simulation: " + simulationClassName
    }
}

// Run Command = & .\gradlew.bat runCaseRetentionForChildObjectsSimulation

// Function to register a task for a simulation
def registerSimulationTask(taskName, simulationClassName) {
    tasks.register(taskName) {
        doLast {
            println "Running simulation: ${simulationClassName}"
        }
        // Set the simulation class and make this task depend on gatlingRun
        finalizedBy(gatlingRun)
        gatlingRun.simulationClassName = simulationClassName
    }
}
// List of simulations with their task names and simulation class names
//MH wish I had known this existed before I spent 20min bashing my head against the wall trying to figure out how to run the R1b simulation.
def simulations = [

    [task: 'runLoginSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.LoginSimulation'],
    [task: 'runCreateAccountSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.CreateAccountSimulation'],
    [task: 'runApproveAccountSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.ApproveAccountSimulation'],
    [task: 'runUserExistsSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.UserExistsSimulation'],
    [task: 'runDeleteAccountSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.DeleteAccountSimulation'],
    [task: 'runMAC_01aSimulation', class: 'simulations.Scripts.PerformanceTests.MAC_01aSimulation'],
    [task: 'runSearchAccountSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.SearchAccountSimulation'], //MH this comma is really important 
    [task: 'runR1bSearchAndViewDefendantSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.R1bSearchAndViewDefendantSimulation'],
    [task: 'runPGSearchAccountSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.PGSearchAccountSimulation'],
    [task: 'runR1bSearchMajorCreditorSimulation', class: 'simulations.Scripts.PerformanceTests.PlayTest.R1bSearchMajorCreditorSimulation']

]

// Register tasks dynamically
simulations.each { simulation ->
    registerSimulationTask(simulation.task, simulation.class)
}


checkstyleGatling {
    maxWarnings = 3035
}

tasks.register('runAllStyleChecks') {
    dependsOn 'checkstyleMain'
    dependsOn 'checkstyleTest'
    dependsOn 'checkstyleGatling'
}
